/**
 * Generated by `scripts/split-catalogues.mjs`. Do not edit by hand.
 *
 * The two things the app needs to know about its twelve languages without holding all
 * twelve in the bundle: which they are, and how complete each one is. The strings
 * themselves are fetched per locale from `/data/copy/<locale>.json`.
 *
 * A test asserts these numbers still match `catalogues.ts`, so editing a translation
 * without re-running the script fails the suite rather than drifting quietly into a
 * language picker that reports a completeness nobody measured.
 */

/** Every locale with a catalogue, English excluded — it is compiled in. */
export const LOCALE_CODES: readonly string[] = ["es","fr","de","it","pt","nl","pl","tr","ru","hi","zh","ja"];

/** How much of the chrome each locale actually translates, 0 to 1. */
export const COVERAGE: Readonly<Record<string, number>> = Object.freeze(
  {
    "es": 0.970037,
    "fr": 0.948814,
    "de": 0.956305,
    "it": 0.961298,
    "pt": 0.971286,
    "nl": 0.953808,
    "pl": 0.963795,
    "tr": 0.967541,
    "ru": 0.978777,
    "hi": 0.980025,
    "zh": 0.980025,
    "ja": 0.980025
  },
);
