/**
 * Write the sitemap, now that records are real pages.
 *
 *   node --experimental-strip-types --import ./scripts/lib/ts-resolve.mjs scripts/emit-sitemap.mjs
 *
 * `public/sitemap.xml` was hand-written and listed six URLs, with a comment explaining
 * why the other seventeen thousand were left out:
 *
 *   > Deliberately not the 17,740 records. They resolve on the client from one index.html,
 *   > so every one of them would offer a crawler the same title and the same description —
 *   > 17,740 URLs that look like duplicates of each other.
 *
 * That reasoning was right and is now out of date: `prerender-records.mjs` writes a file
 * per record with its own title, description and image. The records that were left out of
 * *that* are left out of this for the same reason — a page with nothing recorded on it has
 * nothing for a crawler to rank, and listing it would be asking to be judged as thin
 * content, which is the fault the original comment was avoiding.
 *
 * Written to `dist/` rather than `public/`, because it is now derived. The copy in
 * `public/` is deleted so the two cannot disagree.
 */

import { readFileSync, writeFileSync, existsSync, unlinkSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const DIST = resolve(HERE, '../dist');
const SITE = 'https://wikifoodia.ajailabs.app';

/* With the deferred text put back — this list must match the one `prerender-records.mjs`
   writes, and both are decided by fields that arrive after the first paint. */
import { builtCatalogue } from './lib/built-catalogue.mjs';
import { countryPages } from './lib/country-pages.mjs';

const { catalogue } = await builtCatalogue();

/** The same rule `prerender-records.mjs` applies, so the two lists cannot drift apart. */
const indexed = catalogue.filter(
  (dish) => dish.steps.length > 0 || dish.ingredients.length > 0 || (dish.prepSummary ?? '').trim(),
);

/*
 * Each of these has a real HTML file of its own: `/` from the export, the rest written by
 * `prerender-screens.mjs` with its own title, description and canonical. Before that they
 * were seven URLs sharing one file, which is the duplicate-content fault this list was
 * written to avoid for records.
 *
 * `/propose` is deliberately absent, and so is `/proposals`. Both are disallowed in
 * robots.txt — a crawler following a form spends its budget on inputs rather than on
 * food — and a sitemap that lists a URL robots.txt refuses is a contradiction Search
 * Console reports as an error. They still have prerendered heads, which is what a
 * shared link needs; a page worth sharing is not the same as a page worth indexing.
 */
const SCREENS = [
  ['/', '1.0'],
  ['/atlas', '0.9'],
  ['/browse', '0.8'],
  ['/search', '0.7'],
  ['/how', '0.7'],
  ['/support', '0.5'],
  ['/privacy', '0.4'],
];

/* The countries prerender-countries.mjs wrote a page for, by the same rule. */
const countries = countryPages(catalogue).pages;

const url = (loc, priority) => `  <url><loc>${SITE}${loc}</loc><priority>${priority}</priority></url>`;

const xml = [
  '<?xml version="1.0" encoding="UTF-8"?>',
  '<!--',
  '  Generated by scripts/emit-sitemap.mjs. Do not edit by hand.',
  '',
  `  ${SCREENS.length} screens, ${countries.length} countries and ${indexed.length} records, each of which`,
  '  has a real HTML file',
  '  with its own title, description and canonical — records from prerender-records.mjs,',
  '  screens from prerender-screens.mjs.',
  '',
  `  ${catalogue.length - indexed.length} records are deliberately absent: they hold a name and a place and`,
  '  nothing else, so there is nothing for a crawler to rank and listing them would be',
  '  asking to be judged as thin content. They stay reachable, and say plainly on the page',
  '  that nobody has recorded how they are made.',
  '-->',
  '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
  ...SCREENS.map(([loc, priority]) => url(loc, priority)),
  ...countries.map((entry) => url(`/country/${entry.slug}`, '0.5')),
  ...indexed.map((dish) => url(`/dish/${dish.id}`, '0.6')),
  '</urlset>',
  '',
].join('\n');

writeFileSync(resolve(DIST, 'sitemap.xml'), xml);

/* The hand-written copy, so a stale one cannot be served from `public/`. */
const stale = resolve(HERE, '../public/sitemap.xml');
if (existsSync(stale)) unlinkSync(stale);

process.stdout.write(
  `emit-sitemap: ${SCREENS.length} screens + ${countries.length} countries + ${indexed.length} records ` +
    `(${catalogue.length - indexed.length} left out as unindexable)\n`,
);
