/**
 * The published data's version — generated by `scripts/stamp-data-version.mjs`.
 *
 * Do not edit. It is a hash of everything in `public/data`, and it is appended to every
 * data URL the app fetches so that corrected data arrives at a new address. See the script
 * for why that matters more than it sounds: without it a reader can be served a week-old
 * catalogue and shown badges the atlas has already withdrawn.
 */
export const DATA_VERSION = '4f0dcd0050d8';
